/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.sonartest

class App {
    val greeting: String
        get() {
            return "Hello world."
        }

    fun isOK(a: String): Boolean{
        if (a == "OK"){
            return true
        }
        return false
    }

    fun isOKDuplicated(a: String): Boolean{
        if (a == "OK"){
            return true
        }
        return false
    }

    fun isOKTriplicated(a: String): Boolean{
        if (a == "OK"){
            return true
        }
        return false
    }
}

fun main(args: Array<String>) {
    println(App().greeting)
    println(App().isOK("OK"))
    println(App().isOKDuplicated("NOPE"))
}
