/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.sonartest


import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test


class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test
    fun testAppIsOk() {
        val classUnderTest = App()
        assertEquals(true, classUnderTest.isOK("OK"))
    }
}
